#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COMPOSE_FILE="${SCRIPT_DIR}/docker-compose.yml"
CACHE_FILE="${N8N_ENV_CACHE_FILE:-${SCRIPT_DIR}/n8n-runtime.env}"
RUNTIME_CONTAINER="${N8N_RUNTIME_CONTAINER:-n8n-hxq9-n8n-1}"

INFRA_PROJECT_ID="${INFISICAL_PROJECT_INFRA_ID:-918f6641-7111-4c80-b08a-46321c6b81ab}"
BUSINESS_PROJECT_ID="${INFISICAL_PROJECT_BUSINESS_ID:-f67a6490-4cc1-489d-a6eb-98fe995b0539}"
INFISICAL_ENV="${INFISICAL_ENV:-prod}"
INFISICAL_DOMAIN="${INFISICAL_API_URL:-https://app.infisical.com/api}"

persist_cache() {
  mkdir -p "$(dirname "$CACHE_FILE")"
  : > "$CACHE_FILE"
  chmod 600 "$CACHE_FILE"

  {
    echo "# generated by run_with_infisical.sh"
    while IFS= read -r name; do
      case "$name" in
        DB_*|DD_*|FACEBOOK_*|GEMINI_*|INFISICAL_*|N8N_*|NODES_EXCLUDE|TELEGRAM_*|WEBHOOK_URL|TZ|GENERIC_TIMEZONE|NODE_ENV)
          if [ -n "${!name:-}" ]; then
            printf 'export %s=%q\n' "$name" "${!name}"
          fi
          ;;
      esac
    done < <(compgen -e | sort)
  } > "$CACHE_FILE"
}

load_cache() {
  if [ -f "$CACHE_FILE" ]; then
    # shellcheck disable=SC1090
    . "$CACHE_FILE"
    return 0
  fi
  return 1
}

seed_cache_from_runtime_container() {
  if ! docker inspect "$RUNTIME_CONTAINER" >/dev/null 2>&1; then
    return 1
  fi

  mkdir -p "$(dirname "$CACHE_FILE")"
  {
    echo "# generated from live n8n runtime container"
    docker exec "$RUNTIME_CONTAINER" sh -lc 'env' | while IFS= read -r line; do
      case "$line" in
        DB_*|DD_*|FACEBOOK_*|GEMINI_*|INFISICAL_*|N8N_*|NODES_EXCLUDE=*|TELEGRAM_*|WEBHOOK_URL=*|TZ=*|GENERIC_TIMEZONE=*|NODE_ENV=*)
          key="${line%%=*}"
          value="${line#*=}"
          if [ "$key" = "N8N_RUNNERS_ENABLED" ]; then
            continue
          fi
          printf 'export %s=%q\n' "$key" "$value"
          ;;
      esac
    done
  } > "$CACHE_FILE"
  chmod 600 "$CACHE_FILE"
}

detect_compose_project_name() {
  if [ -n "${COMPOSE_PROJECT_NAME:-}" ]; then
    return 0
  fi

  local project_name
  project_name="$(docker inspect -f '{{ index .Config.Labels "com.docker.compose.project" }}' "$RUNTIME_CONTAINER" 2>/dev/null || true)"
  if [ -n "$project_name" ]; then
    COMPOSE_PROJECT_NAME="$project_name"
    export COMPOSE_PROJECT_NAME
    return 0
  fi
}

login_infisical() {
  if [ -n "${INFISICAL_TOKEN:-}" ]; then
    return 0
  fi

  local client_id client_secret
  client_id="${INFISICAL_CLIENT_ID:-${INFISICAL_RUNTIME_CLIENT_ID:-${INFISICAL_PROVISIONER_CLIENT_ID:-}}}"
  client_secret="${INFISICAL_CLIENT_SECRET:-${INFISICAL_RUNTIME_CLIENT_SECRET:-${INFISICAL_PROVISIONER_CLIENT_SECRET:-}}}"

  if [ -z "$client_id" ] || [ -z "$client_secret" ]; then
    echo "ERROR: Set INFISICAL_TOKEN or INFISICAL_CLIENT_ID/INFISICAL_CLIENT_SECRET first." >&2
    echo "Hint: use the runtime-read identity for n8n startup." >&2
    exit 1
  fi

  INFISICAL_TOKEN="$(infisical login --method=universal-auth --client-id="$client_id" --client-secret="$client_secret" --domain="$INFISICAL_DOMAIN" --plain 2>/dev/null || true)"
  if [ -z "$INFISICAL_TOKEN" ]; then
    return 1
  fi
  export INFISICAL_TOKEN
}

load_path() {
  local project_id="$1"
  local path="$2"
  local dotenv
  dotenv="$(infisical secrets get \
    --token="$INFISICAL_TOKEN" \
    --domain="$INFISICAL_DOMAIN" \
    --projectId="$project_id" \
    --env="$INFISICAL_ENV" \
    --path="$path" \
    --recursive \
    --output dotenv \
    --silent 2>/dev/null || true)"

  if [ -n "$dotenv" ]; then
    set -a
    eval "$dotenv"
    set +a
  fi
}

ensure_runner_token() {
  if [ -n "${N8N_RUNNERS_AUTH_TOKEN:-}" ]; then
    return 0
  fi

  if command -v openssl >/dev/null 2>&1; then
    N8N_RUNNERS_AUTH_TOKEN="$(openssl rand -hex 32)"
  else
    N8N_RUNNERS_AUTH_TOKEN="$(date +%s%N | sha256sum | awk '{print $1}')"
  fi
  export N8N_RUNNERS_AUTH_TOKEN
  echo "INFO: Generated N8N_RUNNERS_AUTH_TOKEN for external n8n task runners." >&2
}

if ! load_cache; then
  if seed_cache_from_runtime_container; then
    load_cache
  elif login_infisical; then
    load_path "$INFRA_PROJECT_ID" "/"
    load_path "$BUSINESS_PROJECT_ID" "/"
    persist_cache
  else
    echo "ERROR: Unable to reach Infisical and no runtime cache/container was available." >&2
    echo "Hint: start the live n8n container once, then rerun so this script can seed the cache." >&2
    exit 1
  fi
fi

if [ -z "${INFISICAL_TOKEN:-}" ]; then
  echo "WARN: proceeding from cached runtime env rather than Infisical." >&2
fi

if [ -n "${INFISICAL_TOKEN:-}" ]; then
  load_path "$INFRA_PROJECT_ID" "/"
  load_path "$BUSINESS_PROJECT_ID" "/"
fi

: "${DD_CLIENT_KEY:=DIAMONDREAMERS}"
export DD_CLIENT_KEY

: "${NODES_EXCLUDE:=[]}"
export NODES_EXCLUDE

unset N8N_RUNNERS_ENABLED

if [ -z "${N8N_EDITOR_BASE_URL:-}" ] || [ "${N8N_EDITOR_BASE_URL:-}" = "http://213.218.240.196:32769/" ] || [ "${N8N_EDITOR_BASE_URL:-}" = "http://127.0.0.1:32769/" ]; then
  N8N_EDITOR_BASE_URL="https://n8n.vizionai.iamvisioncorp.org/"
fi
if [ -z "${WEBHOOK_URL:-}" ] || [ "${WEBHOOK_URL:-}" = "http://213.218.240.196:32769/" ] || [ "${WEBHOOK_URL:-}" = "http://127.0.0.1:32769/" ]; then
  WEBHOOK_URL="https://n8n.vizionai.iamvisioncorp.org/"
fi
export N8N_EDITOR_BASE_URL WEBHOOK_URL

ensure_runner_token
persist_cache

if detect_compose_project_name; then
  exec docker compose -f "$COMPOSE_FILE" up -d --force-recreate n8n n8n-runners
fi

exec docker compose -f "$COMPOSE_FILE" up -d
